openapi: 3.0.0
info:
  title: User API Spec
  version: 1.0.0

paths:
  /api/users:
    post:
      summary: Register User API
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: mastama
              password: rahasia456
              name: Singgih Pratama
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              example:
                data:
                  username: mastama
                  name: Singgih Pratama
        '400':
          description: Error in registration
          content:
            application/json:
              example:
                errors: Username already registered

  /api/users/login:
    post:
      summary: Login User API
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: mastama
              password: rahasia456
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              example:
                data:
                  token: unique-token
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                errors: Username or password wrong

  /api/users/current:
    patch:
      summary: Update User API
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: Mastama Programmer Masa Kini
              password: new password
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              example:
                data:
                  username: mastama
                  name: Mastama Programmer Masa Kini
        '400':
          description: Validation error
          content:
            application/json:
              example:
                errors: Name length max 100

    get:
      summary: Get User API
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              example:
                data:
                  username: mastama
                  name: Singgih Pratama
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                errors: Unauthorized

  /api/users/logout:
    delete:
      summary: Logout User API
      responses:
        '200':
          description: Successful logout
          content:
            application/json:
              example:
                data: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                errors: Unauthorized